name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/xwxqwqpwpawa/kernel_xiaomi_raphael
          kernel-branch: cnb
          config: vendor/xiaomi/raphael.config
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
          anykernel3: true
          release: false
          access-token: ${{ secrets.GITHUB_TOKEN }}
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/ReSukiSU/ReSukiSU
